### ISSUE TITLE
ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by dcuestac** [optilude/jira-cycle-extract#13]
Running with Py2.7 in Windows I'm getting this error:

Fetching issues (this could take some time)
Traceback (most recent call last):
  File "C:\app\Python27\Scripts\jira-cycle-extract-script.py", line 11, in <module>
    load_entry_point('jira-cycle-extract==0.10', 'console_scripts', 'jira-cycle-extract')()
  File "c:\app\python27\lib\site-packages\jira_cycle_extract\cli.py", line 142, in main
    cfd_data = q.cfd(cycle_data)
  File "c:\app\python27\lib\site-packages\jira_cycle_extract\cycletime.py", line 216, in cfd
    np.array(df.values, dtype='<M8[ns]').astype('<M8[D]').astype('<M8[ns]'),
ValueError: cannot convert float NaN to integer

**Comment by optilude** [comment]
Apologies but I am no longer maintaining this. I forked it into https://github.com/DeloitteDigitalUK/jira-agile-metrics which is better in most ways and more widely used and tested. Please try to use that instead. It should be a fairly simple migration.

**Comment by dcuestac** [comment]
Great work!, Thanks!
